CREATE TABLE IF NOT EXISTS public.chart_of_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,
    account_type TEXT NOT NULL,
    beginning_balance NUMERIC DEFAULT 0,
    as_of_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    account_title TEXT NOT NULL,
    debit NUMERIC DEFAULT 0,
    credit NUMERIC DEFAULT 0,
    memo TEXT,
    source_module TEXT,
    source_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
